import "./globals.css";
import "swiper/css"
import 'swiper/css/bundle';
import "aos/dist/aos.css"

import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import AppProvider from "@/components/AppProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const roboto = Roboto({ subsets: ["latin"],weight:'400' });

export const metadata: Metadata = {
  title: "NFT Marketplace - Denovin",
  description: "Generated by next.js & react.js & tailwindcss",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className + ' bg-[#110229] text-white overflow-x-hidden'}>
        <AppProvider>
          <Header/>
          {children}
          <Footer/>
        </AppProvider>
      </body>
    </html>
  );
}
